before:
  hooks:
    - go mod tidy
builds:
  - id: fluvia
    main: ./cmd/fluvia/
    binary: fluvia
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archives:
  - id: archive
    rlcp: true
    files:
      - LICENSE
      - CREDITS
      - README.md
